# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noBus', models.CharField(max_length=30)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carne', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.Bus')),
            ],
        ),
    ]
